spring:
  application:
    name: Preview Kotlin Service

  datasource:
    url: jdbc:h2:mem:pk;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
    initialization-mode: embedded

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show_sql: true
    use_sql_comments: true
    format_sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.format_sql: true

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Seoul

  h2:
    console:
      enabled: true
      path: /pk-console

  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    mode: HTML5
    cache: false
    order: 0

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/"
    enabled-by-default: false
  endpoint:
    info:
      enabled: true
    shutdown:
      enabled: true
    health:
      show-details: always
      show-components: always
